### ISSUE TITLE
APU 1d4

### ISSUE THREAD

**Issue by ptorrent** [mkorthof/pc-engines-apu#1]
Hello,

Installing debian 9 on APU 1d4 failed when he tries to look for network interfaces..

Any ideas ?

![image](https://user-images.githubusercontent.com/6083644/103646239-a55dbe80-4f59-11eb-925f-9d7acf7e00e9.png)

**Comment by mkorthof** [comment]
The RTL8111 driver is not OSS so you need non-free fw. There are Debian images available that have it included. 

Alternatively you could try voyage-linux.
